Repository DeepDive-3rd-Project/Backend, pull requests merged in 2025-02, with the labels that each got.

#2 [chore] 프로젝트 초기 설정
  .gitattributes
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/suggestion.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  team1-api/build.gradle
  team1-api/src/main/java/goorm/deepdive/team1/api/Team1ApiApplication.java
  team1-api/src/main/java/goorm/deepdive/team1/api/config/ApiConfig.java
  team1-api/src/main/resources/application-local.yml
  team1-api/src/main/resources/application-prod.yml
  team1-api/src/main/resources/application.yml
  team1-api/src/test/java/goorm/deepdive/team1/api/Team1ApiApplicationTests.java
  team1-common/build.gradle
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/AdminExceptionCode.java
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/CustomException.java
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/ExceptionCode.java
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/ExceptionResponse.java
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/GlobalExceptionCode.java
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/GlobalExceptionHandler.java
  team1-common/src/main/java/goorm/deepdive/team1/common/log/LoggingInterceptor.java
  team1-common/src/main/java/goorm/deepdive/team1/common/log/NoLogging.java
  team1-common/src/main/java/goorm/deepdive/team1/common/log/util/HttpReqResUtils.java
  team1-common/src/main/java/goorm/deepdive/team1/common/log/util/LoggingUtils.java
  team1-domain/build.gradle
  team1-domain/src/main/java/goorm/deepdive/team1/domain/BaseTimeEntity.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/domain/Address.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/infrastructure/AddressRepository.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistory.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryInterface.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/domain/Admin.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/domain/Role.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/infrastructure/AdminRepository.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/User.java
  team1-domain/src/test/java/goorm/deepdive/team1/domain/Team1DomainApplicationTests.java
  team1-infra/build.gradle
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/base/EnableTeam1Config.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/base/Team1Config.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/base/Team1ConfigGroup.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/base/Team1ConfigImportSelector.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/jpa/JpaAuditingConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/jpa/JpaConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/properties/PropertiesConfig.java
Labels: chore

#4 [#3] 유저 CRUD 구현 및 swagger 설정
  team1-api/build.gradle
  team1-api/src/main/java/goorm/deepdive/team1/api/aspect/ExceptionLoggingAspect.java
  team1-api/src/main/java/goorm/deepdive/team1/api/aspect/ServerErrorLoggingAspect.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserControllerImpl.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/request/UserCreateRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/request/UserUpdateRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserListResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserPersistResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserResponse.java
  team1-common/build.gradle
  team1-common/src/main/java/goorm/deepdive/team1/common/log/LoggingInterceptor.java
  team1-common/src/main/java/goorm/deepdive/team1/common/log/util/LoggingUtils.java
  team1-domain/build.gradle
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/User.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/exception/UserDomainExceptionCode.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/exception/UserNotFoundException.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-infra/build.gradle
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/jpa/JpaConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/impl/UserRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/jpa/JpaUserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/security/SecurityConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/swagger/SwaggerConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/web/WebConfig.java
Labels: feature

#9 [#8] address history crud 구현
  team1-api/build.gradle
  team1-api/src/main/java/goorm/deepdive/team1/api/address/presentation/AddressController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserControllerImpl.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/request/UserCreateRequest.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/application/AddressCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/application/AddressQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/infrastructure/AddressRepository.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistory.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/exception/AddressHistoryDomainExceptionCode.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/exception/AddressHistoryNotFoundException.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryInterface.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryRepository.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/impl/AddressHistoryRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/impl/AddressRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/impl/UserRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/jpa/JpaAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/jpa/JpaAddressRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/repository/jpa/JpaUserRepository.java
Labels: feature

#11 [#10] 더미데이터 생성 api 구현
  team1-api/src/main/java/goorm/deepdive/team1/api/data/DataGeneratorController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/data/DataGeneratorControllerImpl.java
  team1-api/src/main/java/goorm/deepdive/team1/api/data/response/DataGeneratorResponse.java
  team1-api/src/main/resources/application.yml
  team1-infra/build.gradle
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/AsyncConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/DataGenerator.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/AddressHistoryRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/AddressRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/UserRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaAddressRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaUserRepository.java
Labels: feature

#17 [#13] redis, elasticsearch 설정
  team1-api/src/main/java/goorm/deepdive/team1/api/paging/PageableResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/paging/PaginatedListResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserControllerImpl.java
  team1-api/src/main/resources/application.yml
  team1-domain/build.gradle
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/domain/Address.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistory.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistoryCache.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/common/BaseTimeEntity.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/User.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/UserCache.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-infra/build.gradle
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/elastic/ElasticConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/elastic/ElasticProperties.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/jpa/JpaConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/redis/RedisConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/config/redis/RedisProperties.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/UserRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaUserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/redis/RedisAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/redis/RedisUserRepository.java
Labels: refactor

#23 [feat] 유저,주소 테이블 필드 추가 및 기능 수정
  team1-api/src/main/java/goorm/deepdive/team1/api/address/application/AddressFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/address/presentation/request/AddressCreateRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/address/presentation/request/AddressUpdateRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/address/presentation/resonse/AddressResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/kakao/KakaoApiAddressService.java
  team1-api/src/main/java/goorm/deepdive/team1/api/kakao/response/KakaoApiAddressResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/request/UserCreateRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/request/UserUpdateRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserResponse.java
  team1-common/src/main/java/goorm/deepdive/team1/common/exception/InvalidInputException.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/application/AddressCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/domain/Address.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/User.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/UserCache.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/UserDocument.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/enums/Gender.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
Labels: feature, refactor

#31 [#27] 유저 통계 조회 구현
  docker-compose.yml
  team1-api/src/main/java/goorm/deepdive/team1/api/jwt/JwtUtil.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserControllerImpl.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserHeatMapListResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserHeatMapResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/resonse/UserStatsResponse.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/domain/AddressSearch.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/UserDocument.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/domain/enums/AgeGroups.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/elastic/ElasticUserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/UserRepositoryImpl.java
Labels: feature

#34 [refactor] 페이징 페이지 숫자 수정
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserControllerImpl.java
Labels: refactor

#39 [#37] 유저 주소 이력 조회 구현
  team1-api/src/main/java/goorm/deepdive/team1/api/addresshistory/Application/AddressHistoryFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/addresshistory/presentation/response/AddressHistoryListResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/addresshistory/presentation/response/AddressHistoryResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/UserControllerImpl.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistory.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistoryCache.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryRepository.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/config/KafkaConsumerConfig.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/consumer/AddressHistoryConsumer.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/consumer/UserConsumer.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/producer/AddressHistoryProducer.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/AddressHistoryRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/UserRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/redis/RedisAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/redis/RedisUserRepository.java
Labels: refactor

#41 [#36] 삭제 데이터 스케줄링 구현
  team1-api/src/main/java/goorm/deepdive/team1/api/Team1ApiApplication.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryRepository.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/elastic/ElasticUserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/AddressHistoryRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/UserRepositoryImpl.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/jpa/JpaUserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/redis/RedisAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/redis/RedisUserRepository.java
Labels: feature

#43 [#42] 유저 생성 시 입력 데이터 검증 추가
  team1-api/src/main/java/goorm/deepdive/team1/api/user/presentation/request/UserCreateRequest.java
  team1-common/src/main/java/goorm/deepdive/team1/common/valid/PhoneNumber.java
  team1-common/src/main/java/goorm/deepdive/team1/common/valid/PhoneNumberValidator.java
Labels: refactor

#47 [#46] User Domain Layer test code 작성
  build.gradle
  team1-api/build.gradle
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/test/java/goorm/deepdive/team1/api/Team1ApiApplicationTests.java
  team1-domain/build.gradle
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/test/java/goorm/deepdive/team1/domain/Team1DomainApplicationTests.java
  team1-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  team1-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
  team1-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  team1-domain/src/testFixtures/java/user/domain/UserDomainTest.java
Labels: feature

#49 [#48] 유저 정보 수정 로직 수정
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
Labels: refactor

#53 [#51] addresshistory domain layer testcode 작성
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryRepository.java
  team1-domain/src/testFixtures/java/address/domain/AddressDomainTest.java
  team1-domain/src/testFixtures/java/addresshistory/application/AddressHistoryCommandServiceTest.java
  team1-domain/src/testFixtures/java/addresshistory/application/AddressHistoryQueryServiceTest.java
  team1-domain/src/testFixtures/java/addresshistory/domain/AddressHistoryDomainTest.java
  team1-domain/src/testFixtures/java/mock/r/TestEntityUtils.java
  team1-domain/src/testFixtures/java/mock/repository/FakeAddressHistoryRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/AddressHistoryRepositoryImpl.java
Labels: feature

#55 [#50] 관리자 role 변경 api 추가
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/application/AdminFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/AdminController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/AdminControllerImpl.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/request/AdminRoleUpdateRequest.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/application/AdminCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/domain/Admin.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/exception/AdminDomainExceptionCode.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/exception/CannotChangeOwnRoleException.java
Labels: feature

#58 [#57] address index 중복 제거
  team1-domain/src/main/java/goorm/deepdive/team1/domain/address/domain/Address.java
Labels: refactor

#64 [#60] 어드민 로직 수정
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/application/AdminFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/AdminController.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/AdminControllerImpl.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/request/AdminRegisterRequest.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/response/AdminListResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/response/AdminRegisterResponse.java
  team1-api/src/main/java/goorm/deepdive/team1/api/admin/presentation/response/AdminSearchResponse.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/application/AdminCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/application/AdminQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/domain/Admin.java
Labels: refactor

#63 [#62] 서버 배포문제 env 경로 미인식
  team1-api/src/main/java/goorm/deepdive/team1/api/config/PropertyConfig.java
Labels: refactor

#65 [#61] Admin domain layer testcode 작성
  team1-domain/src/main/java/goorm/deepdive/team1/domain/admin/infrastructure/AdminRepository.java
  team1-domain/src/testFixtures/java/admin/application/AdminCommandServiceTest.java
  team1-domain/src/testFixtures/java/admin/application/AdminQueryServiceTest.java
  team1-domain/src/testFixtures/java/admin/domain/AdminDomainTest.java
  team1-domain/src/testFixtures/java/mock/repository/FakeAdminRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/AdminRepositoryImpl.java
Labels: test

#70 [#69] 트랜잭션 처리
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/resources/application-local.yml
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserQueryService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserRepository.java
  team1-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/repository/impl/UserRepositoryImpl.java
Labels: refactor

#72 [#71] 유저 Facade에서 AddressHistory 로직 분리
  team1-api/src/main/java/goorm/deepdive/team1/api/user/application/UserFacade.java
  team1-api/src/main/java/goorm/deepdive/team1/api/user/listener/UserEventListener.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/application/AddressHistoryCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/domain/AddressHistory.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/addresshistory/infrastructure/AddressHistoryProducer.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/application/UserCommandService.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/event/UserCreatedEvent.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/event/UserDeletedEvent.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/event/UserUpdatedEvent.java
  team1-domain/src/main/java/goorm/deepdive/team1/domain/user/infrastructure/UserProducer.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/consumer/KafkaUserConsumer.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/producer/KafkaAddressHistoryProducer.java
  team1-infra/src/main/java/goorm/deepdive/team1/infra/kafka/producer/KafkaUserProducer.java
Labels: refactor

#74 [#73] 더미데이터 위치 좌표 생성 범위 수정
  team1-infra/src/main/java/goorm/deepdive/team1/infra/data/BatchService.java
Labels: refactor
